### ISSUE TITLE
Feature--comment on reports

### ISSUE THREAD

**Issue by nmcox** [csi4999-mims/Website#112]
LE and public need to be able to comment and see comments

**Comment by nmcox** [comment]
ui is done.

**Comment by nmcox** [comment]
Need the database tables to hold the comments @mbroe @apmorey @tcwatling

**Comment by mbroe** [comment]
A migration file for the `comments` table was created in 409caa452b5d6307bef1f0f676081d571d4ef776, but a change is required in the reports controller (see #122).

**Comment by nmcox** [comment]
This is basically done. There is still one bug we need to work out on the server side because it was not working on the dev site.

**Comment by mbroe** [comment]
Issue resolved.  Creating a PR.
