### ISSUE TITLE
Bar chart doesn't show 'Found' count

### ISSUE THREAD

**Issue by mbroe** [csi4999-mims/Website#185]
The bar chart on the LE homepage only shows stats for 'On Hold' and 'In Progress'.  The numbers for 'Found' are always shown as `0`.

**Comment by nmcox** [comment]
This happened when I changed it so the found ones didnt show in the table. The graph and table should both be good to go now.

This is the commit 306cccf

**Comment by mbroe** [comment]
nmcox <notifications@github.com> writes:

> This happened when I changed it so the found ones didnt show in the
> table.  [snip]

I figured they were probably related.  Thanks!
